spring:
  application:
    name: feature-flag-service
  docker:
    compose:
      file: backend/feature-flag-service/compose.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/feature_flags
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # CAUTION: Use 'validate' in prod, 'update' is okay for dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true